application: tw3gsucks
version: 1
runtime: python
api_version: 1
inbound_services:
- warmup

handlers:
- url: /css
  static_dir: css

- url: /payload
  static_dir: payload
  
- url: /signalReport.kml
  script: signalReportKMLGen.py
  
- url: /showMap
  script: signalReportGen.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: reportsignal.py